# Generated by Django 3.1.2 on 2020-10-26 17:19

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descriptions', models.CharField(max_length=1000)),
                ('newFeatures', models.CharField(max_length=500)),
                ('previous_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('priceDescription', models.CharField(max_length=1000)),
                ('serviceImageUrl', models.CharField(max_length=200)),
            ],
        ),
    ]
